### ISSUE TITLE
 Error: Repo not found

### ISSUE THREAD

**Issue by therealcodemonger** [simplicity/snip#1]
<img width="480" alt="repo-not-found-issue" src="https://github.com/user-attachments/assets/6170777a-52cf-4b92-88c8-4c671c3e452c" />

I generated a fine grain access token and provided repo link but stuck at this error.

**Could you provide detailed guide to set the sync?**

**Comment by therealcodemonger** [comment]
Note: Its a private repo for obv reasons

**Comment by samu** [comment]
Hi, thanks for your question. I'm really sorry for the confusion. You don't have to provide the full domain, just your owner name and repo name:

`owner-name/repo-name`
